kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus
  namespace: monitoring
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi