version: 1
config:
  - type: physical
    name: eth0
    subnets:
      - type: static
        address: 192.168.2.150/24
        gateway: 192.168.2.1
        dns_nameservers:
          - 192.168.2.1
          - 8.8.8.8
        dns_search:
          - k8s-master