#cloud-config
# vim: syntax=yaml
#

hostname: k8s-master
manage_etc_hosts: true

users:
  - name: kaeptn
    primary-group: users
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users,docker,adm,dialout,audio,plugdev,netdev,video
    ssh-import-id: None
    lock_passwd: true
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAkbVae6jGuL5cGuxQt1moXuicamCaeJ6RzwYCwnsKlzSMwdF1dJzrRrlIoOZYiI0JfmtVLqLl2AcNKRQYe+np3+Q2FSO6n5JsAIMJA6tQdVKywAJ2kawzJTFxMVa+UR0CHl2dahfUNe+mX4tfbYMJzUzgKldEh/I6Dll/pAhr7BYYbCzRwcaks+MZNjM9SqS3BrSNpyD57Eyg1ldcB4dDQjzzEA4Gy4+yAhiNfeAGovv7CIamh+VtoJKoIaCC+dF11cwMWD3K49NEG6R+CmlqNCZzxRaw37NTijYcTddptUjgNxtzYVXbaZQH1YKbw91DnN/VKdHNsr0aI8qyidjiMPLGdnlByHI88PPu1BD3pjH5JYiqlwn1E2ojACmL1BZE4hfvQX5bKkcNiguNtUjWFHCaRBKkV+PbJMNJ+BnoH55n/H1RvmgKa+wnHlTM8LEyj71IVM3DT41hsHHYl26YvB5Rci2p5qUIsPgUSiMGlWxHZJ/wQ6brwfcwzl8Ab95FMz+LZE0g3F2OoWePbagjLromfd72YYeKPmaMLDVOsNymUBFZ5BVh5WMyR7Py8ehhjxBEvrfhVM6QQOBU5wPl5VLgwTBtHjiBgOCV64KOUG4SqRjtf7uVI7M6esRJv6gU8tfau6+d11mIFccs6oyQRwcAJkzHdcbGwDJX/t68jQ==

locale: "en_US.UTF-8"
timezone: "Europe/Berlin"

package_update: true
package_upgrade: true
package_reboot_if_required: true
package_upgrade: false

runcmd:
  - 'systemctl restart avahi-daemon'

power_state:
  mode: reboot
  timeout: 30
  condition: True